wafRule = {
    '360': [
        're.search("wangzhan\.360\.cn", currentHeader, re.I)',
        '"/wzws-waf-cgi/" in currentText',
        '"360.cn" in currentText',
        '"360.cn" in currentHeader'
    ],
    'airlock': [
        're.search("\AAL[_-]?(SESS|LB)=",currentHeader, re.I)'
    ],
    'anquanbao': [
        're.search("MISS", currentHeader, re.I)',
        '"/aqb_cc/error/" in (currentText)'
    ],
    'armor': [
        '"This request has been blocked by website protection from Armo" in (currentText)'
    ],
    'aws': [
        r're.search("AWS", currentHeader,re.I)'
    ],
    'baidu': [
        r're.search("fhl", currentHeader, re.I)',
        r're.search("yunjiasu-nginx", currentHeader,re.I)'
    ],
    'barracuda': [
        r're.search("\Abarra_counter_session=",currentHeader, re.I)',
        r're.search("(\A|\b)barracuda_",currentHeader, re.I)'
    ],
    'bigip': [
        're.search("\ATS\w{4,}=",currentHeader, re.I)',
        're.search("BigIP|BIGipServe",currentHeader, re.I)',
        're.search("BigIP|BIGipServe", currentHeader,re.I)',
        're.search("\AF5\Z", currentHeader,re.I)'
    ],
    'binarysec': [
        're.search("BinarySec", currentHeader,re.I)'
    ],
    'blockdos': [
        're.search("BlockDos\.net", currentHeader,re.I)'
    ],
    'ciscoacexml': [
        're.search("ACE XML Gateway", currentHeader,re.I)'
    ],
    'cloudflare': [
        're.search("cloudflare-nginx", currentHeader,re.I)',
        're.search("\A__cfduid=",currentHeader, re.I)',
        're.search("CloudFlare Ray ID:|var CloudFlare=", currentText)'
    ],
    'cloudfront': [
        're.search("cloudfront", currentHeader,re.I)',
        're.search("cloudfront", currentHeader,re.I)'
    ],
    'comodo': [
        're.search("Protected by COMODO WAF", currentHeader,re.I)'
    ],
    'datapower': [
        're.search("\A(OK|FAIL)", currentHeader, re.I)'
    ],
    'denyall': [
        're.search("\Asessioncookie=",currentHeader, re.I)',
        're.search("\ACondition Intercepted", currentText, re.I)'
    ],
    'dotdefender': [
        '"dotDefender Blocked Your Request" in (currentText)'
    ],
    'edgecast': [
        're.search("\AECDF", currentHeader,re.I)'
    ],
    'expressionengine': [
        '"Invalid GET Data" in (currentText)'
    ],
    'fortiweb': [
        're.search("\AFORTIWAFSID=",currentHeader, re.I)'
    ],
    'hyperguard': [
        're.search("\AODSESSION=",currentHeader, re.I)'
    ],
    'incapsula': [
        're.search("incap_ses|visid_incap",currentHeader, re.I)',
        're.search("Incapsula", currentHeader, re.I)',
        '"Incapsula incident ID" in (currentText)'
    ],
    'isaserver': [
        '"The server denied the specified Uniform Resource Locator (URL). Contact the server administrator." in (currentText)',
        '"The ISA Server denied the specified Uniform Resource Locator (URL)" in (currentText)'
    ],
    'jiasule': [
        're.search("jiasule-WAF", currentHeader,re.I)',
        're.search("__jsluid=",currentHeader, re.I)',
        're.search("jsl_tracking",currentHeader, re.I)',
        're.search("static\.jiasule\.com/static/js/http_error\.js", currentText, re.I)',
        '"notice-jiasule" in (currentText)'
    ],
    'kona': [
        're.search("Reference #[0-9a-f.]+", currentText, re.I)',
        're.search("AkamaiGHost", currentHeader,re.I)'
    ],
    'modsecurity': [
        're.search("Mod_Security|NOY", currentHeader,re.I)',
        '"This error was generated by Mod_Security" in (currentText)'
    ],
    'netcontinuum': [
        're.search("\ANCI__SessionId=",currentHeader, re.I)'
    ],
    'netscaler': [
        're.search("\Aclose", currentHeader,re.I)',
        're.search("\A(ns_af=|citrix_ns_id|NSC_)",currentHeader, re.I)',
        're.search("\ANS-CACHE",currentHeader,re.I)'
    ],
    'newdefend': [
        're.search("newdefend", currentHeader,re.I)'
    ],
    'nsfocus': [
        're.search("NSFocus", currentHeader,re.I)'
    ],
    'paloalto': [
        're.search("Access[^<]+has been blocked in accordance with company policy", currentText, re.I)'
    ],
    'profense': [
        're.search("\APLBSID=",currentHeader, re.I)',
        're.search("Profense", currentHeader,re.I)'
    ],
    'radware': [
        're.search("Unauthorized Activity Has Been Detected.+Case Number:", currentText, re.I | re.S)'
    ],
    'requestvalidationmode': [
        '"ASP.NET has detected data in the request that is potentially dangerous" in (currentText)',
        '"Request Validation has detected a potentially dangerous client input value" in (currentText)'
    ],
    'safe3': [
        're.search("Safe3WAF",currentHeader, re.I)',
        're.search("Safe3 Web Firewall", currentHeader,re.I)'
    ],
    'safedog': [
        're.search("WAF/2\.0",currentHeader, re.I)',
        're.search("Safedog", currentHeader,re.I)',
        're.search("safedog",currentText, re.I)',
        '"safedog.cn" in (currentText)'
    ],
    'secureiis': [
        're.search("SecureIIS[^<]+Web Server Protection", currentText)',
        '"http://www.eeye.com/SecureIIS/" in (currentText)',
        're.search("\?subject=[^>]*SecureIIS Erro", currentText)'
    ],
    'senginx': [
        '"SENGINX-ROBOT-MITIGATION" in (currentText)',
    ],
    'sitelock': [
        '"SiteLock Incident ID" in (currentText)'
    ],
    'sonicwall': [
        '"This request is blocked by the SonicWALL" in (currentText)',
        r're.search("Web Site Blocked.+\bnsa_banne", currentText, re.I)',
        're.search("SonicWALL", currentHeader,re.I)'
    ],
    'sophos': [
        '"Powered by UTM Web Protection" in (currentText)'
    ],
    'stingray': [
        're.search("\AX-Mapping-",currentHeader, re.I)'
    ],
    'sucuri': [
        're.search("Sucuri/Cloudproxy", currentHeader,re.I)',
        '"Sucuri WebSite Firewall - CloudProxy - Access Denied" in (currentText)',
        're.search("Questions\?.+cloudproxy@sucuri\.net", (currentText))'
    ],
    'tencent': [
        '"waf.tencent-cloud.com" in (currentText)'
    ],
    'teros': [
        're.search("\Ast8(id|_wat|_wlf)",currentHeader, re.I)'
    ],
    'trafficshield': [
        're.search("F5-TrafficShield", currentHeader,re.I)',
        're.search("\AASINFO=",currentHeader, re.I)'
    ],
    'urlscan': [
        're.search("Rejected-By-UrlScan",currentHeader, re.I)',
        're.search("/Rejected-By-UrlScan", currentText, re.I)'
    ],
    'uspses': [
        're.search("Secure Entry Serve", currentHeader,re.I)'
    ],
    'varnish': [
        're.search("varnish\Z",currentHeader,re.I)',
        're.search("varnish", currentHeader,re.I)',
        're.search("\bXID: \d+", currentText)'
    ],
    'wallarm': [
        're.search("nginx-wallarm", currentHeader,re.I)'
    ],
    'webknight': [
        're.search("WebKnight", currentHeader,re.I)'
    ],
    'yundun': [
        're.search("YUNDUN", currentHeader,re.I)',
        're.search("YUNDUN", currentHeader,re.I)'
    ],
    'yunsuo': [
        're.search("<img class=\"yunsuologo\"", currentText, re.I)',
        're.search("yunsuo_session",currentHeader, re.I)'

    ],
    '存在未识别WAF': [
        '"您所提交的请求含有".encode("utf-8") in (currentText)',
        '"如果您是网站管理员点击这里查看详情".encode("utf-8") in (currentText)',
        '"已被网站管理员设置拦截！".encode("utf-8") in (currentText)',
        '"注入拦截".encode("utf-8") in (currentText)',
        '"您的请求带有".encode("utf-8") in (currentText)'
        '"包含危险的攻击请求".encode("utf-8") in (currentText)'
    ]}
