# coding=utf-8

from spider import BaseSpider
import functools
import asyncio
import aiodns

resolver_nameservers = ['114.114.114.114', '114.114.115.115']
resolver_timeout = 5.0
limit_resolve_conn = 100


def aiodns_resolver():
    return aiodns.DNSResolver(nameservers=resolver_nameservers, timeout=resolver_timeout)


class Domain2ipSpider(BaseSpider):
    def __init__(self, domain, name, domain_list):
        super().__init__()
        self.name = name
        self.source = 'Domain2ipSpider'
        self.domain = domain
        self.ip_2_doamin_list = list()
        for _ in domain_list:
            self.ip_2_doamin_list.append({'subdomain': _, 'ip': ''})

    def resolve_callback(self, future, index, datas):
        try:
            result = future.result()
        except Exception as e:
            datas[index]['ip'] = ''  # 解析错误会默认返回空， 获取报错信息str(e.args)
        else:
            if isinstance(result, tuple):
                _, answers = result
                if answers:
                    ips = answers[0].host  # 这里解析到的ip就拿一个
                    datas[index]['ip'] = str(ips)

    async def aiodns_query_a(self, hostname, semaphore=None):
        if semaphore is None:
            resolver = aiodns_resolver()
            answers = await resolver.query(hostname, 'A')
            return hostname, answers
        else:
            async with semaphore:
                resolver = aiodns_resolver()
                answers = await resolver.query(hostname, 'A')
                return hostname, answers

    async def bulk_query_a(self, datas):
        task_list = []
        semaphore = asyncio.Semaphore(limit_resolve_conn)
        for i, data in enumerate(datas):
            if not data.get('ip'):
                subdomain = data.get('subdomain')
                task = asyncio.ensure_future(self.aiodns_query_a(subdomain, semaphore))
                task.add_done_callback(functools.partial(self.resolve_callback, index=i, datas=datas))  # 回调填充
                task_list.append(task)

        if task_list:  # 任务列表里有任务不空时才进行解析
            await asyncio.wait(task_list)  # 等待所有task完成
        self.res_list = self.get_unique_list(datas)
        self._is_continue = False

    async def spider(self):
        await self.bulk_query_a(self.ip_2_doamin_list)
        self.write_file(self.get_unique_list(self.res_list), 4)

    async def main(self):
        await self.spider()
        return self.res_list


if __name__ == '__main__':
    domainList = ['zx.lishui.gov.cn',
                  'web.dcyun.com',
                  'www.lshqyy.com',
                  'zjls2.app.lsnews.com.cn',
                  'photo.lsnews.com.cn',
                  'www.lsnews.com.cn',
                  'www.lsol.com.cn',
                  'www.lscszh.com',
                  'lsdzzm.zjzwfw.gov.cn',
                  'iot.lszwfw.cn',
                  'ls.578.cn',
                  'oa.lishui.gov.cn',
                  'tysw.dsj.lishui.gov.cn',
                  'lsszzf.lishui.gov.cn',
                  'daj.lishui.gov.cn',
                  'www.2113515.com.cn',
                  'dhyjs.lsszzf.lishui.gov.cn',
                  'qyxtfz.lsszzf.lishui.gov.cn',
                  'yshj.lsszzf.lishui.gov.cn',
                  'xxczh.lsszzf.lishui.gov.cn',
                  'lsld.top',
                  'lszsyt.mememe.cn',
                  'lsszjsc.zjrongxiang.com',
                  'tysw.dsj.lishui.gov.cn',
                  'szsh.fgw.lishui.gov.cn',
                  'fgw.lishui.gov.cn',
                  'www.zjlscourt.com',
                  'www.lsfby.com.cn',
                  'ylws.lsga.lishui.gov.cn',
                  'www.lswater.cn',
                  'gzw.lishui.gov.cn',
                  'sjgswj.lishui.gov.cn',
                  'jkzx.lishui.gov.cn',
                  'zhbg.lsjw.gov.cn',
                  'jw.lishui.gov.cn',
                  'jw.lishui.gov.cn',
                  'mapi.zjzwfw.gov.cn',
                  'www.lsqpgl.cn',
                  'jsj.lishui.gov.cn',
                  'jtj.lishui.gov.cn',
                  'res.zjlsedu.org',
                  'jczx.zjlsedu.org',
                  'jyj.lishui.gov.cn',
                  'xyd.jrb.lishui.gov.cn',
                  'sjrb.lishui.gov.cn',
                  'xtbs.lishui.gov.cn',
                  'jxj.lishui.gov.cn',
                  '93xs.lishui.gov.cn',
                  'cxy.bianguo.com.cn',
                  'sti.kjj.lishui.gov.cn',
                  'www.kjj.lishui.gov.cn',
                  'kjj.lishui.gov.cn',
                  'lsysf.scxcfz.cn',
                  'www.bszgjgy.com',
                  'mapi.zjzwfw.gov.cn',
                  'www.cnnice.com',
                  'lsaafs.ac.cn',
                  'www.lssgyun.com',
                  'dg.shanshan360.com',
                  'lsxczx.lsszzf.lishui.gov.cn',
                  'lsszzf.lishui.gov.cn',
                  'www.lszhsn.com',
                  'www.lsqx.com',
                  'zj.cma.gov.cn',
                  'smart.zj121.com',
                  'www.lqjt.com',
                  'rd.lishui.gov.cn',
                  'sbrf.rfb.lishui.gov.cn',
                  'rfb.lishui.gov.cn',
                  'lsshebao.yyhj.zjzwfw.gov.cn',
                  'activity.96225.com',
                  'rsj.lishui.gov.cn',
                  'smk.lshrss.cn',
                  'rsks.lishui.gov.cn',
                  'www.ls-hospital.com',
                  'www.lishui.gov.cn',
                  'applets.lscoffee.net',
                  'sswj.lishui.gov.cn',
                  'sjj.lishui.gov.cn',
                  'hb.lishui.gov.cn',
                  'zhcy.lishui.gov.cn',
                  'gsj.lishui.gov.cn',
                  'www.057812365.cn',
                  'www.ls12315.com',
                  'zjlssf.com',
                  'sgpt.zjwater.com',
                  'ls.sifa365.cn',
                  '12348ls.zjsft.gov.cn',
                  'sfj.lishui.gov.cn',
                  'tb.lishui.gov.cn',
                  'tyj.lishui.gov.cn',
                  'laobinghome.cn',
                  'qtb.lishui.gov.cn',
                  'sbw.lishui.gov.cn',
                  'www.zxngmgjd.com',
                  'lssz.lishui.gov.cn',
                  'dx.lishui.gov.cn',
                  'gmuser.zjzwfw.gov.cn',
                  'ggxn.lszwfw.cn',
                  'bldzs.lszwfw.cn',
                  'www.lslndx.cn',
                  'zjcsyy.tzb.lishui.gov.cn',
                  'tzb.lishui.gov.cn',
                  'weblishui.zyh365.com',
                  'lishuigov.vcgvip.com',
                  'szfz.zfw.lishui.gov.cn',
                  'www.zjls12380.gov.cn',
                  'dd.lsxfw.cn',
                  'mapi.zjzwfw.gov.cn',
                  'www.zgsxlm.cn',
                  'wsjsw.lishui.gov.cn',
                  'jkls.gov.cn',
                  'www.jkls.gov.cn',
                  'lssl.feekr.com',
                  'zlbyjy2.0578homestay.com',
                  'whls.lsszzf.lishui.gov.cn',
                  'www.lsszbwg.com',
                  'www.lsswhg.cn',
                  'lsart.com.cn',
                  'www.lslyzxw.cn',
                  'www.lsbwg.com',
                  'whdz.lsart.com.cn',
                  'lishui-szwhg.chaoxing.com',
                  'lszjcs.zjzwfw.gov.cn',
                  'jyzx.lssggzy.com',
                  'zzd.lssggzy.lishui.gov.cn',
                  'lssggzy.lishui.gov.cn',
                  'xzsp.lishui.gov.cn',
                  'lssggzy.lishui.gov.cn',
                  'aqsc.lsszzf.lishui.gov.cn',
                  'jgdgw.lishui.gov.cn',
                  'www.lsjyjc.com',
                  'fsk.zjszdsys.com',
                  'www.lshospital.zj.cn',
                  'www.lsszyy.com.cn',
                  'gtj.lishui.gov.cn',
                  'ygb.zrzyj.lishui.gov.cn',
                  'dzyb.zjgem.cn',
                  'yw.lvguxy.com',
                  'zhzf.zfj.lishui.gov.cn',
                  'zfj.lishui.gov.cn',
                  'zgh.lishui.gov.cn',
                  'zghsmz.lishui.gov.cn',
                  'bm.qsng.cn',
                  'www.lsszqxh.com',
                  'www.lsart.com.cn',
                  'lsu.edu.cn',
                  'my.lib.lsu.edu.cn',
                  'my.lsu.edu.cn',
                  'zcw.lishui.gov.cn',
                  'trys.baitutech.com',
                  'www.shzdhbsb.com',
                  'lsmm.lishui.gov.cn',
                  'f.eral.cn',
                  'www.eral.com',
                  'szsng.lsqsng.cn',
                  'bm.qsng.cn',
                  'zgoutes.com',
                  'www.zjwk.com',
                  'www.lishuisoft.com',
                  'lssafety.com',
                  'www.lshr.com',
                  'www.lswzsh.com',
                  'nancheng360.com',
                  'kfq.admin.lszhengyi.com',
                  'kfq.lishui.gov.cn',
                  'szzf.kfq.lishui.gov.cn',
                  'szhgg.kfq.lishui.gov.cn',
                  'f74o9g.axshare.com',
                  'manage.yh.lszhengyi.com',
                  'hbegj.kfq.lishui.gov.cn',
                  'real4d.xyz',
                  'www.jinfull.com',
                  'szjj.kfq.lishui.gov.cn',
                  'zsgl.kfq.lishui.gov.cn',
                  'kh.baitusoft.com',
                  'szfz.kfq.lishui.gov.cn',
                  'lskfq.zjcoms.cn',
                  'www.fdm.com.cn',
                  'www.cnksk.com',
                  'www.zjslhb.com',
                  'www.jieanrobot.com',
                  'www.ultech.cc',
                  'www.evbev.cn',
                  'szsh.liandu.gov.cn',
                  'ld.zjlscourt.com',
                  'lsldhw.cloudhw.cn',
                  'www.liandu.gov.cn',
                  'liandu.lsjc.gov.cn',
                  'ldszsy.liandu.gov.cn',
                  'szsm.liandu.gov.cn',
                  'xwy.liandu.gov.cn',
                  'szjj.liandu.gov.cn',
                  'ldzfc.zjrongxiang.com',
                  'lsldygpj.com',
                  'lw.ld96345.com',
                  'liandu.zjnydsj.com',
                  'szmh.liandu.gov.cn',
                  'www.liandu.gov.cn',
                  'lsygzz.bfdigitsapi.com',
                  'scxcfz.cn',
                  'ldnys.liandu.gov.cn',
                  'zhsl.liandu.gov.cn',
                  'www.ldlibrary.com',
                  '9cloud.lszhengyi.com',
                  'xsdwmsj.ldwmsj.com',
                  'eds.lszwfw.cn',
                  'dj.baitutech.com',
                  'library.hwmao.cn',
                  'bookss.ldlibrary.com',
                  'lsxdx.bfdigitsapi.com',
                  'ldnews.zjol.com.cn',
                  'lszgh.bfdigitsapi.com',
                  'www.ldwhg.cn',
                  'longowine.com',
                  'www.zjssjt.com',
                  'www.lcyyls.com',
                  'www.zjrxyy.cn',
                  'rcy.longquan.gov.cn',
                  'dtkj.longquan.gov.cn',
                  'zfpy.longquan.gov.cn',
                  'qcsc.longquan.gov.cn',
                  'zhhw.longquan.gov.cn',
                  'web.dcyun.com',
                  'sgpt.zjwater.com',
                  'jydt.jkls.gov.cn',
                  'lqsrmyy-ddjy-h5.juyizhilian.com',
                  'nzl.longquan.gov.cn',
                  'ilongquan.lszwfw.cn',
                  'lqfy-back.zhihuipk.com',
                  'ylfn.hzgzsoft.com',
                  'www.longquan.gov.cn',
                  'zylh.zjcloud.com',
                  'www.lqmtrb.com.cn',
                  'www.lqrmyy.cn',
                  'www.lqqcyjy.com',
                  'szfz.longquan.gov.cn',
                  'www.lq0578.com',
                  'lqnews.zjol.com.cn',
                  'szfz.yunhe.gov.cn',
                  'yun.zjyhedu.org',
                  'web.dcyun.com',
                  'szsh.yunhe.gov.cn',
                  'xmgl.yunhe.gov.cn',
                  'szyn.yunhe.gov.cn',
                  'aqhi.yunhe.gov.cn',
                  'szyh.yunhe.gov.cn',
                  'yhjy.1000liu.com',
                  'www.yunhe.gov.cn',
                  'www.yhwjw.com',
                  'www.yhqsng.com.cn',
                  '2018.lsphoto.org',
                  'zgyhnews.zjol.com.cn',
                  'szjj.yunhe.gov.cn',
                  'www.yhurb.com',
                  'www.yhxrmyydc.com',
                  'www.qingyuanodr.cn',
                  'szfz.zjqy.gov.cn',
                  'zcjn.zjqy.gov.cn',
                  'qynews.zjol.com.cn',
                  'szggmh.zjqy.gov.cn',
                  'szzf.zjqy.gov.cn',
                  'www.zjqy.gov.cn',
                  'yida-pro.ding.zj.gov.cn',
                  'qingyuanwt.zssite.cn',
                  'yjcj.zjqy.gov.cn',
                  'www.qyxyjglj.com',
                  'web.dcyun.com',
                  'web.dcyun.com',
                  'qyall.appleiosapp.top',
                  'qyzfj.zjqy.gov.cn',
                  'szjj.zjqy.gov.cn',
                  'szsh.zjqy.gov.cn',
                  'dzzz.zjqy.gov.cn',
                  'tzxm.zjzwfw.gov.cn',
                  'www.zjmzqy.com',
                  'www.cnshzm.com',
                  'demo.zjzdy.net',
                  'zjpassport.zbglxt.com',
                  'j.4yankj.cn',
                  'szhgg.qingtian.gov.cn',
                  'newoa.qt.ls.local',
                  'qtsd.qingtian.gov.cn',
                  'qtdjdt.lsxfw.cn',
                  'www.aioclinic.com',
                  'szsh.qingtian.gov.cn',
                  'www.zgqtsw.cn',
                  'www.qtpec.com',
                  'szjj.qingtian.gov.cn',
                  'qt.yunland.cn',
                  'szfz.qingtian.gov.cn',
                  'www.zgqt.zj.cn',
                  'qtkxyy.com',
                  'www.qingtian.gov.cn',
                  'www.abckids.com.cn',
                  'www.lsflsb.cn',
                  'djxh5.zjyolion.com',
                  'jcwghpt.jingning.gov.cn',
                  'zlsxgf.gtc315.cn',
                  'rpt.gtc315.cn',
                  'szjn600.jingning.gov.cn',
                  'msa.jingning.gov.cn',
                  'hli.jingning.gov.cn',
                  'www.jingning.gov.cn',
                  'qlzs.jingning.gov.cn',
                  'sxlzw.jingning.gov.cn',
                  'www.jnqsng.cn',
                  'www.jnbctv.com',
                  'www.jnyzb.net',
                  'www.fuhuibao.club',
                  'www.sxjnsss.com',
                  'szsh.songyang.gov.cn',
                  'zxyjs.kaidexinlian.com',
                  'songyang.zjddpg.com',
                  '101.133.195.133',
                  'syzz.jw.chaoxing.com',
                  'songyang.zjddpg.com',
                  'szjj.songyang.gov.cn',
                  'songyang.zjdmwh.cn',
                  'www.syhospital.cn',
                  'tyxf.songyang.gov.cn',
                  'szportal.songyang.gov.cn',
                  'sywz.zgsynews.com',
                  'syxww.zjol.com.cn',
                  'szfz.songyang.gov.cn',
                  'zfwpaqz.songyang.gov.cn',
                  'tyxf.songyang.gov.cn',
                  'dlgcl.songyang.gov.cn',
                  'sy.aipsybot.com',
                  'village.songyang.gov.cn',
                  'www.songyang.gov.cn',
                  'szzf.songyang.gov.cn',
                  'zfjcfxt.songyang.gov.cn',
                  'www.yzmgf.com',
                  'www.zjsyhtrb.com',
                  'lssjczlspt.zfw.lishui.gov.cn',
                  'szfz.suichang.gov.cn',
                  'wzztc.scxnews.cn',
                  'tg.suichang.gov.cn',
                  'zmh.suichang.gov.cn',
                  'newoa.sc.ls.local',
                  'szsh.fgj.suichang.gov.cn',
                  'scfy.kaidexinlian.com',
                  'scjgsw.com',
                  'tg.suichang.gov.cn',
                  'jwstatic.zjjcy.gov.cn',
                  'zhhw.suichang.gov.cn',
                  'szjj.suichang.gov.cn',
                  'www.scrmyy.com',
                  'www.suichang.gov.cn',
                  'bzh.zjdyit.com',
                  'www.xlhb.com',
                  'scnews.zjol.com.cn',
                  'www.ilimin.com.cn',
                  'www.lmkggf.com',
                  'www.zjkan.com',
                  'www.scfmbank.com',
                  'www.cnxingchang.com',
                  'www.jycsw.cn',
                  'www.jyhcw.cn',
                  'www.jyczbank.com',
                  'wz.jynews.com.cn',
                  'jyszsh.jinyun.gov.cn',
                  'ju.zjzdy.net',
                  'zjjy.zbglxt.com',
                  'jinyunwt.zssite.cn',
                  'jyjrzhfw.jinyun.gov.cn',
                  'thingcom.com',
                  'jinyunyanglao.com',
                  'www.jinyunmzj.com',
                  'lsxj.baitutech.cn',
                  'sgpt.zjwater.com',
                  'jyfwm.jinyun.gov.cn',
                  'mapi.zjzwfw.gov.cn',
                  'jqb.jinyun.gov.cn',
                  'jyszfz.jinyun.gov.cn',
                  'jyzmh.jinyun.gov.cn',
                  'jyszzf.jinyun.gov.cn',
                  'www.jinyun.gov.cn',
                  'website.shwread.cn',
                  'www.jyzyzz.com',
                  'www.jynews.com.cn',
                  'ljy.lishui.gov.cn',
                  'www.chinacooker.com']
    loop = asyncio.get_event_loop()
    asyncio.set_event_loop(loop)
    dddd = Domain2ipSpider('zjhu.edu.cn', 'test', domainList)
    t = loop.run_until_complete(dddd.main())
    print(t)
